awb/urls.py
from django.contrib import admin
from django.urls import path
from . import views 
from . import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home' ),
    path('contact-us/', views.contact_us, name='contact-us'),
    path('login/', views.login, name='login'),
    path('admin-electeam/', views.admin, name='admin'),
    path('admin-electeam/profile/', views.profile, name='profile'),
    path('admin-electeam/services/', views.services, name='services'),
    path('admin-electeam/services/add/', views.add_service, name='add-service'),
    path('admin-electeam/delete-g-image/', views.delete_g_image, name='delete-g-image'),
    path('admin-electeam/delete-service/', views.delete_service, name='delete-service'),

 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

form/models.py
from django.db import models

# Create your models here.

class INFO(models.Model):
    welcome = models.TextField()
    description = models.TextField()
    main_image = models.ImageField()
    video = models.FileField()

class Service(models.Model):
    title = models.CharField(max_length=50)
    paragraph = models.TextField()

class ServiceImage(models.Model):
    service = models.ForeignKey('Service', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='services/')

class GalleryImage(models.Model):
    image = models.ImageField(upload_to='gellery/')

class ContactUs(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    fname = models.CharField(max_length=50)
    email = models.TextField(max_length=50)
    message = models.TextField(max_length=1000)

form/forms.py
from django import forms
from .models import GalleryImage

class GalleryImageForm(forms.ModelForm):
    class Meta:
        model = GalleryImage
        fields = ['image',]

awb/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from form.models import ContactUs, Service, ServiceImage, INFO, GalleryImage
from django.contrib import messages as MSG
from django.core.mail import EmailMessage
from django.template.loader import render_to_string


def is_authenticated(request):
    if request.session.get('is_authenticated'):
        pass
    else:
        raise Http404


def home(request):
    info = INFO.objects.all()[0]
    context = {
        'gallery_images' : GalleryImage.objects.all().order_by('-id'),
        'info' : info,
        'services' : Service.objects.all().order_by('-id')
    }
    return render(request, 'base.html', context)



def contact_us(request):
    if request.method == 'POST':
        fname = request.POST.get('name').strip()
        email = request.POST.get('email').strip()
        message = request.POST.get('message').strip()
        if fname  and email and message:
            ContactUs.objects.create(
                fname = fname,
                email = email,
                message = message
            )
            message = render_to_string('email.html', {
                'fname' : fname,
                'email' : email,
                'message' : message
            })
            email_message = EmailMessage(subject="Email from site", body=message, from_email='hafidlazar45@gmail.com', to=["electeam.ec@gmail.com"])
            email_message.send()
            return HttpResponse()
        else:
            raise
    return redirect('home')

def admin(request):
    is_authenticated(request)
    return render(request, 'admin.html')

def login(request):
    if request.method == 'POST':
        if request.POST.get('password') == 'electeam-991$' and request.POST.get('email') == "elec@team.com":
            request.session['is_authenticated'] = True
            return redirect('admin')
    
    return render(request, 'login.html')

def profile(request):
    is_authenticated(request)
    info = INFO.objects.all()[0]
    if request.method == "POST":
        info.welcome = request.POST.get('welcome').strip()
        info.description = request.POST.get('description').strip()
        try:
            image = request.FILES.get('image')
            if image:

                image.name = 'main_image' + "." + image.name.split('.')[-1]
                info.main_image.delete()
                info.main_image = image
            video = request.FILES.get('video')
            if video:
                video.name = 'video' + "." + video.name.split('.')[-1]
                info.video .delete()
                info.video = video
            info.save()

            for image in request.FILES.getlist('gallery_images'):
                image_model = GalleryImage.objects.create()
                image.name = str(image_model.id) + "." + image.name.split('.')[-1]
                image_model.image = image
                image_model.save()

            MSG.success(request, 'Profile updated successfuly.')
        except:
            MSG.error(request, 'Profile was not updated successfuly.')
    
    context = {
        'gallery_images' : GalleryImage.objects.all().order_by('-id'),
        'info' : info,
    }
    return render(request, 'profile.html', context)

def services(request):
    is_authenticated(request)
    services = Service.objects.all().order_by('-id')
    context = {
        'services' : services
    }
    return render(request, 'services.html', context)

def add_service(request):
    is_authenticated(request)
    if request.method == 'POST':
        title = request.POST.get('title').strip()
        description = request.POST.get('description').strip()
        images = request.FILES.getlist('service_images')
        if title and description:
            try:
                service = Service.objects.create(
                    title = title,
                    paragraph = description
                )
                for image in images:
                    image_model = ServiceImage.objects.create(
                        service = service
                    )
                    image.name = str(image_model.id) + "." +image.name.split('.')[-1]
                    image_model.image = image
                    image_model.save()
                MSG.success(request, 'Service was created successfully')
                
            except:
                MSG.warning(request, 'Service was not created')
        return redirect('services')
    return render(request, 'add_service.html')

def delete_service(request):
    is_authenticated(request)
    id = int(request.GET.get('id'))
    Service.objects.get(id=id).delete()
    return HttpResponse('')

def delete_g_image(request):
    is_authenticated(request)
    id = int(request.GET.get('id'))
    GalleryImage.objects.get(id=id).delete()
    return HttpResponse('')

form/views.py
from django.shortcuts import render

# Create your views here.

templates/add_service.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Services</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body>
    {% if messages %}
    <div onclick="this.remove()" class="messages p-3 m-3 border rounded btn btn-outline-success col-12">
        {% for message in messages %}
        <div >{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    
    <form enctype="multipart/form-data" action="" method="POST" class="p-3 border m-3 rounded" style="padding-bottom: 75px !important;;">
          {% csrf_token %}
          <h1 class="pb-4" onclick="window.location.href='{% url 'services' %}'" style="cursor: pointer;"> 
            <img src="https://img.icons8.com/ios/100/null/circled-left-2.png"/>
            Go Back
          </h1>
          <div class="p-3 rounded border">
            <label for="">Title</label>
            <input type="text" name="title" id="" class="form-control">
            <label for="" class="mt-3">Description</label>
            <textarea name="description" id=""  class="form-control" cols="30" rows="10"></textarea>
            <label for="" class="mt-3">Images</label>
            <div class="mt-2">
                <input type="file" accept="image/*" multiple name='service_images' class="form-control col-12 border rounded p-3" id="exampleFormControlFile3">
            </div>
          </div>
          <button class="btn btn-outline-success mt-3" style="float: right">Create</button>
    </form>   
    <style>
      label{
        font-weight: bold;
        font-size: 1.2rem;
      }
    </style>
</body>
</html>

templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
</head>
<body>
    <div style="padding: 15px; margin:15px; border: 2px solid #c8bc38; border-radius: 5px; display: flex; flex-wrap: wrap; flex-direction: column;">
        <div style="padding: 15px; margin:15px; border: 2px solid #c8bc38; text-align: center; border-radius: 5px" onclick="window.location.href='{% url "profile" %}'">
            Profile 
        </div>
        <div style="padding: 15px; margin:15px; border: 2px solid #c8bc38; text-align: center; border-radius: 5px" onclick="window.location.href='{% url "services" %}'">
            Services
        </div>
        <div style="padding: 15px; margin:15px; border: 2px solid #c8bc38; text-align: center; border-radius: 5px"  onclick="window.location.href=''">
            Your Posts
        </div>
        <div style="padding: 15px; margin:15px; border: 2px solid #c8bc38; text-align: center; border-radius: 5px"  onclick="window.location.href=''">
            Create Post 
        </div>
        
    </div>
</body>

<style>
    div > div:hover,
    div > div:active{
        background-color: #c8bc38;
        color: white;
        cursor: pointer;
    }
</style>
</html>

templates/email.html
{% autoescape off %}

  Name : {{ fname }}
  Email : {{ email }}
  message : {{ message }}

{% endautoescape %}

templates/login.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Services</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body>
    {% if messages %}
    <div onclick="this.remove()" class="messages p-3 m-3 border rounded btn btn-outline-success col-12">
        {% for message in messages %}
        <div >{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    
    <form  action="" method="POST" class="p-3 border m-3 rounded" style="padding-bottom: 75px !important;;">
        {% csrf_token %}
        <input type="text" placeholder="Email" name="email" id="" class="form-control my-3">
        <input name="password" id="" type="password" placeholder="Password" class="form-control  my-3">
        <button class="btn btn-outline-success mt-3" style="float: right">Login</button>
    </form>   
    <style>
      label{
        font-weight: bold;
        font-size: 1.2rem;
      }
    </style>
</body>
</html>

templates/profile.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body>
    {% if messages %}
    <div onclick="this.remove()" class="messages p-3 m-3 border rounded btn btn-outline-success col-12">
        {% for message in messages %}
        <div >{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    
    <form enctype="multipart/form-data" action="" method="POST" class="p-3 border m-3 rounded" style="padding-bottom: 75px !important;;">
          {% csrf_token %}
          <h1 class="pb-4" onclick="window.location.href='{% url 'admin' %}'" style="cursor: pointer;"> 
            <img src="https://img.icons8.com/ios/100/null/circled-left-2.png"/>
            Go Back
          </h1>
          <div class="mb-3 p-2 ">
            <label for="exampleFormControlInput1" class="form-label">Welcome Text</label>
            <input type="text" class="form-control" name="welcome" id="exampleFormControlInput1" value='{{ info.welcome }}'>
          </div>
          <div class="mb-3 p-2 ">
            <label for="exampleFormControlTextarea1" class="form-label">Description</label>
            <textarea class="form-control" name='description' id="exampleFormControlTextarea1" rows="3">{{ info.description }}</textarea>
          </div>
          <div class="mb-3 p-2 border rounded">
            <label for="exampleFormControlFile1" class="form-label">Main Image</label>
            <div class="p-3 rounded border mb-3">Current file: <a href="{{ info.main_image.url }}" target="_blank">{{ info.main_image.url }}</a></div>
            <input type="file" accept="image/*"  name='image' class="form-control col-12 border rounded p-3" id="exampleFormControlFile1">
          </div>
          <div class="mb-3 p-2 border rounded">
            <label for="exampleFormControlFile2" class="form-label">Main Video</label>
            <div class="p-3 rounded border mb-3">Current file: <a href="{{ info.video.url }}" target="_blank">{{ info.video.url }}</a></div>
            <input type="file" accept="video/*" name='video' class="form-control col-12 border rounded p-3" id="exampleFormControlFile1">
          </div>
          <div class="p-3 rounded border mb-3 mt-5">
            <label class="mb-3">Gallery images(21:9)</label>
            <div style="display: flex; flex-direction: column; overflow-x: auto; max-height: 500px;">
              <div class="m-auto">
                {% for image in gallery_images %}
                  <div style="position: relative;" id="image_div_{{ image.id }}">
                    <img class="gallery-image" onclick="delete_image({{image.id}})" style="position: absolute; left: 10px; top: 10px; width: 40px; border-radius: 3px; cursor: pointer;" src="https://img.icons8.com/material-sharp/96/FA5252/x-coordinate.png"/>
                    <img src="{{ image.image.url }}" style="flex-shrink: 0; max-height: 200px; max-width: 100%; margin: 15px;" alt="">
                  </div>
                {% endfor %}
              </div>
            </div>
            <label class="mb-3"> Add Images</label>
            <div>
              <input type="file" accept="image/*" multiple name='gallery_images' class="form-control col-12 border rounded p-3" id="exampleFormControlFile3">
            </div>
          </div>
          <button class="btn btn-outline-success mt-3" style="float: right">Update</button>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script>
      function delete_image(id){
        document.getElementById('image_div_' + id).remove()
        $.ajax({
          url: "{% url 'delete-g-image' %}",
          data: {
            id : id
          }
        })
      }
    </script>
    <style>
      label{
        font-weight: bold;
        font-size: 1.2rem;
      }
    </style>
</body>
</html>

templates/services.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Services</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body>
    {% if messages %}
      <div onclick="this.remove()" class="messages p-3 m-3 border rounded btn btn-outline-success col-12">
          {% for message in messages %}
          <div >{{ message }}</div>
          {% endfor %}
      </div>
    {% endif %} 
    <div class="p-3 border m-3 rounded">
          {% csrf_token %}
          <h1 class="pb-4" onclick="window.location.href='{% url 'admin' %}'" style="cursor: pointer;"> 
            <img src="https://img.icons8.com/ios/100/null/circled-left-2.png"/>
            Go Back
          </h1>
          <div class="m-3 text-center border" style="cursor: pointer;" onclick='window.location.href="{% url 'add-service' %}"'>
            <img src="https://img.icons8.com/ios-glyphs/90/null/macos-maximize.png"/>
          </div>
          {% for service in services %}
            <div class="p-3 rounded border" style="position: relative;" id="service_div_{{ service.id }}">
                <img class="gallery-image" onclick="delete_service({{service.id}})" style="position: absolute; right: 10px; top: 10px; width: 40px; border-radius: 3px; cursor: pointer;" src="https://img.icons8.com/material-sharp/96/FA5252/x-coordinate.png"/>
                <label for="">{{ service.title }}</label>
                <p class="mt-2">{{ service.paragraph }}</p>
                <div  class="mt-3" style="display: flex; overflow-x: auto;">
                    {% for image in service.serviceimage_set.all %}
                        <img src="{{ image.image.url }}" alt="" style="max-height: 200px; margin-right: 20px;">
                    {% endfor %}   
                </div>
                
            </div>
          {% endfor %}
    </div>
   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script>
      function delete_service(id){
        document.getElementById('service_div_' + id).remove()
        $.ajax({
          url: "{% url 'delete-service' %}",
          data: {
            id : id
          }


        })
      }
    </script>
    <style>
      label{
        font-weight: bold;
        font-size: 1.2rem;
      }
    </style>
</body>
</html>